apiVersion: apps/v1
kind: Deployment
metadata:
  name: gods-unchained-api
  labels:
    app: gods-unchained-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gods-unchained-api
  template:
    metadata:
      labels:
        app: gods-unchained-api
    spec:
      containers:
      - name: gods-unchained-api
        image: lucasrigobello/gods-unchained-api
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m