apiVersion: v1
kind: Service
metadata:
  name: gods-unchained-api-service
spec:
  selector:
    app: gods-unchained-api
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer